// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NhW4TSD355IKsIWSoU7M8YfWOGpw_EY',
    appId: '1:600758725316:web:0548b877f0115b30c13791',
    messagingSenderId: '600758725316',
    projectId: 'isaamportfolio',
    authDomain: 'isaamportfolio.firebaseapp.com',
    storageBucket: 'isaamportfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-cdETa0uimCU4_ChXzkAQpje0snyCyw',
    appId: '1:600758725316:android:26934ccbb3d90fabc13791',
    messagingSenderId: '600758725316',
    projectId: 'isaamportfolio',
    storageBucket: 'isaamportfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPioWIO59Eta6JCGNS1Kl3hj36CuPMRI',
    appId: '1:600758725316:ios:8246475757585fc3c13791',
    messagingSenderId: '600758725316',
    projectId: 'isaamportfolio',
    storageBucket: 'isaamportfolio.firebasestorage.app',
    iosBundleId: 'com.pearl.miportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPioWIO59Eta6JCGNS1Kl3hj36CuPMRI',
    appId: '1:600758725316:ios:8246475757585fc3c13791',
    messagingSenderId: '600758725316',
    projectId: 'isaamportfolio',
    storageBucket: 'isaamportfolio.firebasestorage.app',
    iosBundleId: 'com.pearl.miportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3NhW4TSD355IKsIWSoU7M8YfWOGpw_EY',
    appId: '1:600758725316:web:f92952302ed5876ec13791',
    messagingSenderId: '600758725316',
    projectId: 'isaamportfolio',
    authDomain: 'isaamportfolio.firebaseapp.com',
    storageBucket: 'isaamportfolio.firebasestorage.app',
  );
}
